#+title: ChangeLog of wowee
#+author: James Dyer
#+email: captainflasmr@gmail.com
#+language: en
#+options: ':t toc:nil author:nil email:nil num:nil title:nil
#+todo: TODO DOING | DONE
#+startup: showall

This document contains the release notes for each tagged commit on the
project's main git repository: [[https://github.com/captainflasmr/wowee]].

With a roadmap and issues also supplied

* Versions

** v0.3.4 <2024-07-19>

feat: Add xref navigation functions and keybindings

- Introduced xref_find_references(), xref_go_back(), and xref_find_definitions() functions in commands.ahk for navigation.
- Assigned new keybindings in keybinds-core.ahk:
  - Alt+. for xref_find_definitions()
  - Alt+, for xref_go_back()
  - Alt+? for xref_find_references()

** v0.3.3 <2024-07-01>

A little support for Notepad++:

- isearch
- comment line

** v0.3.2 <2024-07-01>

Separated individual ergonomic key-mappings as thus:

- wowee--caps_to_ctrl.ahk
- wowee--ralt_to_ctrl.ahk

These are extra files that can be run in addition to the main wowee.ahk for some common ergonomic keyboard Emacs mappings.

** v0.3.1 <2024-06-30>

This commit has added windows, frames support

- kill frame (C-x c)
- split window vertically (C-x 3)
- maximize window (C-x 1)
- next window (C-x o)
- suspend frame (C-z)
- reorganisation of kanban

** v0.3.0 <2024-06-28>

This commit has split out ahk files into apps, core and init:

- Added comment-line
- Added mark-whole-buffer
- Refined isearch
- Added application specific bindings in keybinds-apps.ahk for Visual Studio and VSCode
- Update README to reflect design changes
- Added beginning_of_buffer and end_of_buffer core mappings
- Added mark_whole_buffer core mapping

** v0.2.0 <2024-06-26>

This commit introduces several new functions to enhance the usability and
functionality of the `commands.ahk` script. Notable additions include:

- Implementation of `isearch_backward` and `isearch_forward` functions for improved search capabilities, allowing for backwards and forwards in-document searches with initialization and continuation logic.
- Addition of `recenter_line`, `indent_line`, and `backward_kill_word` functions to enrich text editing commands.
- Enhancement of `select_line` and `goto_line` functions for better line selection and navigation.
- The `quit_g` function extends quitting capabilities to also reset the `selecting` and `searching` states.
- Modifications to `next_lines` and `previous_lines` to increase the number of lines navigated with each command from 3 to 6, improving scroll efficiency.
- Update to `kill_ring_save` to include an escape key press, ensuring a more comprehensive cleanup post-operation.
- Improved the README.org kanban to more easily differentiate between command sections and to define those commands I am not implementing (IGNORE) and those additional commands (EXTRA)

** v0.1.0 <2024-06-19>

Initial version

* Testing

Run wowee.ahk on Windows and perform emacs like commands in various applications.

* Validation

Autohotkey raises no errors when running.
